src/Entity/Abus.php
<?php

namespace App\Entity;

use App\Repository\AbusRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AbusRepository::class)]
class Abus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Encodage = null;

    #[ORM\ManyToOne(inversedBy: 'abuses')]
    private ?Internaute $Internaute = null;

    #[ORM\ManyToOne(inversedBy: 'abuses')]
    private ?Commentaire $Commentaire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEncodage(): ?\DateTimeInterface
    {
        return $this->Encodage;
    }

    public function setEncodage(?\DateTimeInterface $Encodage): self
    {
        $this->Encodage = $Encodage;

        return $this;
    }

    public function getInternaute(): ?Internaute
    {
        return $this->Internaute;
    }

    public function setInternaute(?Internaute $Internaute): self
    {
        $this->Internaute = $Internaute;

        return $this;
    }

    public function getCommentaire(): ?Commentaire
    {
        return $this->Commentaire;
    }

    public function setCommentaire(?Commentaire $Commentaire): self
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }
}

src/Entity/Bloc.php
<?php

namespace App\Entity;

use App\Repository\BlocRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlocRepository::class)]
class Bloc
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\OneToOne(mappedBy: 'Bloc', cascade: ['persist', 'remove'])]
    private ?Position $position = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPosition(): ?Position
    {
        return $this->position;
    }

    public function setPosition(?Position $position): self
    {
        // unset the owning side of the relation if necessary
        if ($position === null && $this->position !== null) {
            $this->position->setBloc(null);
        }

        // set the owning side of the relation if necessary
        if ($position !== null && $position->getBloc() !== $this) {
            $position->setBloc($this);
        }

        $this->position = $position;

        return $this;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VilleRepository::class)]
class Ville
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $VilleName = null;

    #[ORM\ManyToOne(inversedBy: 'villes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Region $region = null;

    #[ORM\ManyToOne(inversedBy: 'villes')]
    private ?CodePostal $codePostal = null;

    #[ORM\OneToMany(mappedBy: 'ville', targetEntity: Utilisateur::class)]
    private Collection $utilisateurs;

    public function __construct()
    {
        $this->utilisateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVilleName(): ?string
    {
        return $this->VilleName;
    }

    public function setVilleName(string $VilleName): self
    {
        $this->VilleName = $VilleName;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getCodePostal(): ?CodePostal
    {
        return $this->codePostal;
    }

    public function setCodePostal(?CodePostal $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getUtilisateurs(): Collection
    {
        return $this->utilisateurs;
    }

    public function addUtilisateur(Utilisateur $utilisateur): self
    {
        if (!$this->utilisateurs->contains($utilisateur)) {
            $this->utilisateurs->add($utilisateur);
            $utilisateur->setVille($this);
        }

        return $this;
    }

    public function removeUtilisateur(Utilisateur $utilisateur): self
    {
        if ($this->utilisateurs->removeElement($utilisateur)) {
            // set the owning side to null (unless already changed)
            if ($utilisateur->getVille() === $this) {
                $utilisateur->setVille(null);
            }
        }

        return $this;
    }

    public Function __toString(){
        
        return $this->codePostal;
    }
    
}

templates/block/categorie_mois.twig
<div class = "categorie_mois">
  <h2>Catégorie du mois</h2>
  <div class="card text-bg-dark">
  {% for image in images %}
      
      {% if image.categorie != null %}
      
        {% if image.categorie.id == categ_mois.id  %}
        <div class= 'container_image'>
        
        <img src="img/categorie/{{image.imageName}}" class="card-img-top" alt="{{image.imageName}}">
        
       </div>
      
        {% endif %}   
         
      {% endif %}
    {% endfor %}
   
    <div class="contenu_categ_mois">
      <h5 class="card-title">{{categ_mois.nom}}</h5>
      <p class="card-text">{{categ_mois.description}}</p>
    </div>
  </div>
</div>

templates/block/categoriesListe.twig
<div class='list-category'>
  <h2>Liste des catégories</h2>
  <ul class="button-list">
    {% for categorie in categories %}
      <li>
        <a href="{{path('app_categorie_de_services', {id: categorie.id })}}">
          {{categorie.nom}} 
        </a>
      </li>
    {% endfor %}    
  </ul>  
</div>

templates/block/footer.twig
<div class="container">
  <footer class="py-5">
    <div class="row">     

      <div class="col-6 offset-md-1 mb-3">
        <form>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Souscrire à notre newsletter</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn mt-1" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>&copy; 2022 Company, Inc. All rights reserved.</p>
      
    </div>
  </footer>
</div>

templates/block/menu.twig
<div class="border-bottom ">
    <div class="container h-header">
        <div class= "logo-container ">
            <img src="{{asset('img/logo.jpg')}}" class="logo" alt="">
        </div>
        <div class="container_menu">       
            <span id="menuHamburger" class="h-hamburger-icon">
                <span class="fa fa-bars"></span>                
            </span>
            <div id="mainMenu" class="navigation">
                <nav class='h-nav'>
                    <ul class="h-nav-ul">
                        <li class='btn'><a href="{{path('app_home')}}">Home</a></li>
                        <li class='btn'><a href="{{path('app_404')}}">A propos</a></li>
                        <li class='btn'><a href="{{path('app_prestataire')}}">Partenaire</a></li>
                        <li class='btn'><a href="{{path('app_home')}}">Par région</a></li>
                        <li class='btn'><a href="{{path('app_404')}}">Stages</a></li>
                        <li class='btn'><a href="{{path('app_404')}}">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>              
        <div class="dropdown icon_login">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
            </button>
            <ul class="dropdown-menu"> 
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li><a class="dropdown-item" href="{{path('app_logout')}}">déconnexion</a></li>
            {% endif %}
            {% if is_granted('IS_AUTHENTICATED_FULLY') == false %}
            <li><a class="dropdown-item" href="{{path('app_login')}}">Connexion</a></li>
            {% endif %}                   
                
                <li><a class="dropdown-item" href="{{path('register')}}">Créer un compte</a></li>
            </ul>
        </div>          
    </div>
</div>

templates/block/prestataire_recent.twig
<div class="Prestataire récent">
  <h1>Prestataire récent</h1>
  
  
<ul class="button-list">
  
    {% for prestataire in prestataires %}
    <li>
      
    <div class="card" style="width: 18rem;">
    {% for image in images %}
      
      {% if image.prestataire != null %}
      
        {% if image.prestataire.id == prestataire.id  %}
        
        <img src="img/logo/{{image.imageName}}" class="card-img-top" alt="{{image.imageName}}">
        {% else %}
        <img src="..." class="card-img-top" alt="pas de logo">
      
        {% endif %}   
         
      {% endif %}
    {% endfor %}
    <div class="card-body">
      <h5 class="card-title">{{prestataire.nom}}</h5>
      <p class="card-text">{{prestataire.utilisateur.ville.villeName}}</p>
      <a href="{{path('app_prestataire_details', {id: prestataire.id})}}" class="btn">Détails</a>
    </div>
  </div>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

templates/block/ruban.twig
<div class="ruban_container"> 
  <div class="ruban"> 
  </div>
</div>

templates/block/search.twig
<header  class="bg-light py-3 mb-4 border-bottom containerSearch">
  <div class="container d-flex flex-wrap justify-content-center">  

    <div class="container containerSearch_form ">
              
          {{ form_start(form,  {'attr': {'class': 'row formSearch'}}) }}
            <div class=" formPrestaire formInput">
              {{ form_row(form.prestataire) }}
            </div>
            <div class=" formInput formRegion">
              {{ form_row(form.region, {'attr': {'class': 'select_region', 'id':'region'}}) }}
            </div>
            <div class=" formInput formVille">
              {{ form_row(form.ville, {'attr': {'class': 'select_ville'}}) }}
            </div>
            <div class="formInput formCp">  
              {{ form_row(form.codePostal, {'attr': {'class': 'select_codePostal'}}) }} 
            </div>
            <div class=" formInput formSubmit">
              <button type="submit" class="btn">Recherche</button>     
            </div>        
          {{ form_end(form) }}      
    </div>
  </div>
</header>

templates/block/test.twig
{% block content %}



  <h1>
    je suis un test .... 
  </h1>          

{% endblock content %}